addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.2.1")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.0.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.7")
addSbtPlugin("fr.qux" % "sbt-release-tags-only" % "0.5.0")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "2.1.146")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.6.0")